const hotels = [
  {
    id: "sample-hotel-shanghai",
    name: "上海示例滨江酒店",
    englishName: "Sample Riverside Hotel Shanghai",
    brand: "示例品牌",
    city: "上海",
    country: "中国",
    address: "上海市浦东新区示例路 1 号",
    hotelCode: "sample-sha",
    lat: 31.2357,
    lng: 121.4998,
    coordinateStatus: "exact",
    isDeflagged: false,
    stayedAt: "2024-05",
    notes: "公开模板示例数据，可删除或替换。",
    userAlias: "上海示例酒店",
    province: "上海",
    group: "Sample Group"
  },
  {
    id: "sample-hotel-hangzhou",
    name: "杭州示例湖畔酒店",
    englishName: "Sample Lakeside Hotel Hangzhou",
    brand: "示例精选",
    city: "杭州",
    country: "中国",
    address: "杭州市西湖区示例街 8 号",
    hotelCode: "sample-hgh",
    lat: 30.246,
    lng: 120.1503,
    coordinateStatus: "exact",
    isDeflagged: false,
    stayedAt: "2024-08",
    notes: "用于演示酒店列表、筛选和地图 marker。",
    userAlias: "杭州示例酒店",
    province: "浙江",
    group: "Sample Group"
  },
  {
    id: "sample-hotel-kyoto",
    name: "京都示例町屋旅宿",
    englishName: "Sample Machiya Stay Kyoto",
    brand: "Independent",
    city: "京都",
    country: "日本",
    address: "Kyoto sample address",
    hotelCode: "sample-ukyo",
    lat: 35.0116,
    lng: 135.7681,
    coordinateStatus: "exact",
    isDeflagged: false,
    stayedAt: "2025-03",
    notes: "海外酒店示例，可按自己的住宿记录替换。",
    userAlias: "京都示例旅宿",
    region: "京都府",
    group: "Independent"
  }
];
