// Manual city/place supplements for the public Footprint template.
// Replace these examples with your own visited cities or destinations.
const places = [
  {
    id: "sample-place-shanghai",
    manualId: "sample-place-shanghai",
    type: "city",
    name: "上海",
    country: "中国",
    province: "上海",
    region: "",
    latitude: 31.2304,
    longitude: 121.4737,
    coordinateStatus: "city-center",
    visitCount: 2,
    firstVisitYear: 2024,
    lastVisitYear: 2025,
    visitYears: [2024, 2025],
    tags: ["示例", "城市"],
    note: "公开模板示例城市。",
    source: "template-example",
    hotelsInCity: [],
    hotelCount: 0,
    groupCount: 0,
    brandCount: 0,
    groupsInCity: [],
    brandsInCity: [],
    sourceLabel: "模板示例"
  },
  {
    id: "sample-place-hangzhou",
    manualId: "sample-place-hangzhou",
    type: "city",
    name: "杭州",
    country: "中国",
    province: "浙江",
    region: "",
    latitude: 30.2741,
    longitude: 120.1551,
    coordinateStatus: "city-center",
    visitCount: 1,
    firstVisitYear: 2024,
    lastVisitYear: 2024,
    visitYears: [2024],
    tags: ["示例"],
    note: "用于演示城市足迹。",
    source: "template-example",
    hotelsInCity: [],
    hotelCount: 0,
    groupCount: 0,
    brandCount: 0,
    groupsInCity: [],
    brandsInCity: [],
    sourceLabel: "模板示例"
  },
  {
    id: "sample-place-chengdu",
    manualId: "sample-place-chengdu",
    type: "city",
    name: "成都",
    country: "中国",
    province: "四川",
    region: "",
    latitude: 30.5728,
    longitude: 104.0668,
    coordinateStatus: "city-center",
    visitCount: 1,
    firstVisitYear: 2025,
    lastVisitYear: 2025,
    visitYears: [2025],
    tags: ["示例"],
    note: "可替换为自己的目的地。",
    source: "template-example",
    hotelsInCity: [],
    hotelCount: 0,
    groupCount: 0,
    brandCount: 0,
    groupsInCity: [],
    brandsInCity: [],
    sourceLabel: "模板示例"
  },
  {
    id: "sample-place-kyoto",
    manualId: "sample-place-kyoto",
    type: "city",
    name: "京都",
    country: "日本",
    province: "",
    region: "京都府",
    latitude: 35.0116,
    longitude: 135.7681,
    coordinateStatus: "city-center",
    visitCount: 1,
    firstVisitYear: 2025,
    lastVisitYear: 2025,
    visitYears: [2025],
    tags: ["示例", "海外"],
    note: "海外目的地示例。",
    source: "template-example",
    hotelsInCity: [],
    hotelCount: 0,
    groupCount: 0,
    brandCount: 0,
    groupsInCity: [],
    brandsInCity: [],
    sourceLabel: "模板示例"
  }
];
