// Public template railway trip examples. Replace with your own records.
window.railTrips = [
  {
    id: "sample-rail-2024-06-01-g7315",
    date: "2024.06.01",
    departureTime: "2024-06-01 09:12",
    departureTimeZone: "Asia/Shanghai",
    trainNo: "G7315",
    trainType: "高铁",
    fromStation: "上海虹桥",
    toStation: "杭州东",
    fromCity: "上海",
    toCity: "杭州",
    fromRegionCode: "CN",
    toRegionCode: "CN",
    seatType: "二等座",
    priceCurrency: "CNY",
    priceValue: 73,
    distanceKm: 169,
    changeFlag: "",
    status: "completed",
    source: "template-example",
    sourceLabel: "模板示例",
    note: "示例铁路记录，可删除。"
  },
  {
    id: "sample-rail-2024-09-18-c2205",
    date: "2024.09.18",
    departureTime: "2024-09-18 14:05",
    departureTimeZone: "Asia/Shanghai",
    trainNo: "C2205",
    trainType: "城际",
    fromStation: "北京南",
    toStation: "天津西",
    fromCity: "北京",
    toCity: "天津",
    fromRegionCode: "CN",
    toRegionCode: "CN",
    seatType: "二等座",
    priceCurrency: "CNY",
    priceValue: 54.5,
    distanceKm: 120,
    changeFlag: "",
    status: "completed",
    source: "template-example",
    sourceLabel: "模板示例",
    note: "示例城际记录。"
  },
  {
    id: "sample-rail-2025-02-10-g6208",
    date: "2025.02.10",
    departureTime: "2025-02-10 16:20",
    departureTimeZone: "Asia/Shanghai",
    trainNo: "G6208",
    trainType: "高铁",
    fromStation: "深圳北",
    toStation: "广州南",
    fromCity: "深圳",
    toCity: "广州",
    fromRegionCode: "CN",
    toRegionCode: "CN",
    seatType: "二等座",
    priceCurrency: "CNY",
    priceValue: 74.5,
    distanceKm: 102,
    changeFlag: "",
    status: "completed",
    source: "template-example",
    sourceLabel: "模板示例",
    note: "用于演示铁路筛选、排序和地图线路。"
  }
];
